spring.application.name=Educational Quality Project

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://mongo:XdnCdkmKwzJiKHiryTDzdgRGOxzNQYtA@crossover.proxy.rlwy.net:24258/qualidade_software?authSource=admin&authMechanism=SCRAM-SHA-256

# Server Configuration
server.port=8080